CIRCLE_SPEED = 50;
TRIANGLE_SPEED = 50;
SQUARE_SPEED = 50;

CIRCLE_SIZE = 40;
TRIANGLE_SIZE = 40;
SQUARE_SIZE = 40;

CIRCLE_TYPE = "circle";
TRIANGLE_TYPE = "triangle";
SQUARE_TYPE = "square";

FRICTION = 0.97;
WORLD_WIDTH = 1500;
WORLD_HEIGHT = 1500;

MAX_WORLD_SNAPSHOT = 20;
